name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: latest
          standalone: true

      - name: Install Dependencies
        run: pnpm install

      - name: Check Format
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Test Action
        uses: ./
